server:
  port: 8082

spring:
  application:
    name: sorteio

  datasource:
    url: jdbc:postgresql://localhost:5432/sorteio
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
